#!/bin/bash

source ${ALLSKY_HOME}/mock_variables

echo "$(date +'%T') MOCK: > $0: $@" >> ${ALLSKY_HOME}/mock_output
echo "$(date +'%T') MOCK: > $0: $@"
bash -x ./scripts/saveImage.sh_original $@
RET=$?
echo "$(date +'%T') MOCK: > $0: RET=$RET"

exit 0
