#!/bin/bash

source ${ALLSKY_HOME}/mock_variables

echo "$(date +'%T') MOCK: > $0: $@" >> ${ALLSKY_HOME}/mock_output

if [ "$1" == "poll" ]; then
	# sunwait poll angle -9 48.18N 13.80E   returns DAY or NIGHT
  echo "$(date +'%T') MOCK: < $0: ${ALLSKY_MOCK_SUNWAIT}" >> ${ALLSKY_HOME}/mock_output
	echo "${ALLSKY_MOCK_SUNWAIT}"
else
  echo "$(date +'%T') MOCK: < $0: unsupported parameter ${1}" >> ${ALLSKY_HOME}/mock_output
	echo "sunwait_mock: unsupported parameter ${1}"
fi
exit 0
